#!/bin/bash
. /home/lemp.conf

# Kiểm tra xem cơ sở dữ liệu lempCheckDB đã tồn tại chưa
if [ -f /var/lib/mysql/lempCheckDB/db.opt ]; then
    rm -rf /var/lib/mysql/lempCheckDB
fi

# Tạo tạm thời cấu hình để tạo cơ sở dữ liệu
cat > "/tmp/config.temp" <<END
CREATE DATABASE lempCheckDB COLLATE utf8_general_ci;
END

# Thực hiện lệnh tạo cơ sở dữ liệu
mariadb -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

# Kiểm tra lại xem cơ sở dữ liệu đã được tạo hay chưa
if [ ! -f /var/lib/mysql/lempCheckDB/db.opt ]; then
    clear
    echo "========================================================================"
    echo "MariaDB service is not running"
    echo "------------------------------------------------------------------------"
    echo "LEMP trying to start it"
    echo "------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 5 ; clear

    # Xóa các file log
    rm -rf /var/lib/mysql/ib_logfile0
    rm -rf /var/lib/mysql/ib_logfile1

    # Khởi động lại MariaDB
    echo "Starting MariaDB service..."
    systemctl start mariadb.service

    clear
    echo "========================================================================"
    echo "Check MariaDB service once again!"
    echo "------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 5 ; clear

    # Tạo lại cơ sở dữ liệu sau khi khởi động lại
    cat > "/tmp/config.temp" <<END
CREATE DATABASE lempCheckDB COLLATE utf8_general_ci;
END

    mariadb -u root -p$mariadbpass < /tmp/config.temp
    rm -f /tmp/config.temp

    # Kiểm tra xem cơ sở dữ liệu đã được tạo chưa
    if [ ! -f /var/lib/mysql/lempCheckDB/db.opt ]; then
        clear
        echo "========================================================================"
        echo "LEMP cannot start MariaDB service"
        sleep 4 ;
        clear
        echo "========================================================================="
        echo "Sorry, LEMP không thể khởi động được MariaDB Service"
        /etc/lemp/menu/tienich/lemp-restart-service
    else
        rm -rf /var/lib/mysql/lempCheckDB
        clear
        echo "========================================================================="
        echo "MariaDB service has been restarted successfully."
        systemctl restart mariadb.service
        echo "MariaDB is running now."
        /etc/lemp/menu/tienich/lemp-restart-service
    fi
else
    rm -rf /var/lib/mysql/lempCheckDB
    clear
    echo "========================================================================="
    echo "Restarting MariaDB service..."
    systemctl restart mariadb.service
    echo "MariaDB service has been restarted successfully."
    /etc/lemp/menu/tienich/lemp-restart-service
fi
