#!/bin/bash
. /home/lemp.conf

# Kiểm tra trạng thái của nginx
if [ "$(systemctl is-active nginx)" == "active" ]; then
    clear
    echo "========================================================================"
    echo "Restarting Nginx service..."
    systemctl restart nginx
    /etc/lemp/menu/tienich/lemp-restart-service
else
    clear
    echo "========================================================================"
    echo "Nginx service is not running"
    echo "------------------------------------------------------------------------"
    echo "LEMP trying to start it"
    echo "------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 5; clear
    echo "-------------------------------------------------------------------------"
    systemctl start nginx
    clear
    echo "========================================================================"
    echo "Checking Nginx service once again!"
    echo "------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 5; clear

    # Kiểm tra lại trạng thái sau khi khởi động
    if [ "$(systemctl is-active nginx)" == "active" ]; then
        clear
        echo "========================================================================"
        echo "Nginx service started successfully."
        /etc/lemp/menu/tienich/lemp-restart-service
    else
        clear
        echo "========================================================================"
        echo "LEMP cannot start Nginx Service"
        sleep 4
        clear
        echo "========================================================================="
        echo "Rất tiếc, LEMP không thể khởi động lại Nginx!"
        /etc/lemp/menu/tienich/lemp-restart-service
    fi
fi
