#!/bin/bash
prompt="Lua chon cua ban (0-Thoat): "
#options=( "Thay Password Root" "Fix Loi Chmod, Chown" "Find Top Largest Files & Folders" "Service Running & Ram Use" "Kiem Tra IP/Nameserver Website" \
#"File Size Converter " "Kiem Tra Thong Tin Server" "Cai Dat Server Timezone" "Install / Remove Imagick" "Cai Dat Htop" \
#"Backup Config File & Vhost" "Thay Doi Port SSH Number" "Config SSH Timeout" "Block Exploits, SQL Injections" "Deny Run Script In Upload Folder" \
#"Dat Mat Khau Bao Ve Folder" "BAT/TAT Email Thong Bao Login" "BAT/TAT Auto Run lemp" "Canh Bao Full Disc Tren Menu" "Restart Service" "TocDo.net" \
#"Varnish Cache" "Update All Website Wordpress" "Install Composer" "Go Bo (Remove) lemp" )
options=( "Thay Password Root" "Tim file va thu muc lon nhat" "Service Running & Ram Use" "Kiem Tra IP/Nameserver Website" \
"File Size Converter " "Kiem Tra Thong Tin Server" "Cai Dat Server Timezone" "Install / Remove Imagick" "Cai Dat Htop" \
"Backup Config File & Vhost" "Thay Doi Port SSH Number" "Config SSH Timeout" "Block Exploits, SQL Injections" "Deny Run Script In Upload Folder" \
"Dat Mat Khau Bao Ve Folder" "BAT/TAT Email Thong Bao Login" "BAT/TAT Auto Run lemp" "Canh Bao Full Disc Tren Menu" "Restart Service" "TocDo.net" \
"Varnish Cache" "Update All Website Wordpress" "Install Composer" "Cai dat them phien ban PHP" "Go cai dat phien ban PHP" "Go Bo (Remove) lemp" )
printf "=========================================================================\n"
printf "                LEMP - Quan Ly VPS/Server by LEMP.VN \n"
printf "=========================================================================\n"
printf "                           Tien Ich - Addons\n"
printf "=========================================================================\n"

# In ra danh sach lua chon theo 2 cot
column_count=2
index=1
for ((i=0; i<${#options[@]}; i+=column_count)); do
    for ((j=0; j<column_count; j++)); do
        if [ $((i + j)) -lt ${#options[@]} ]; then
            printf "%-40s" "$((i + j + 1)). ${options[i + j]}"
        fi
    done
    echo
done

PS3="$prompt"

# Lay lua chon tu nguoi dung
read -p "$PS3" choice


case "$choice" in
	1) /etc/lemp/menu/lemp-doi-pass-root-vps;;
	#2) /etc/lemp/menu/tienich/lemp-sua-loi-chown;; # tam thoi an di
	2) /etc/lemp/menu/tienich/lemp-xem-danh-sach-max-dung-luong-file-menu;;
	3) /etc/lemp/menu/tienich/lemp-dich-vu-dang-chay-va-ram-dung;;
	4) /etc/lemp/menu/tienich/lemp-tim-ip-nameserver-website;;
	5) /etc/lemp/menu/lemp-chuyen-doi-don-vi-file-size-convert;;
	6) /etc/lemp/menu/tienich/lemp-view-thong-tin-ip-vps;;
	7) clear && /etc/lemp/menu/lemp-thay-doi-thong-tin-thoi-gian;; 
	8) /etc/lemp/menu/tienich/lemp-before-imagick;;
	#10) /etc/lemp/menu/tienich/lemp-before-ioncube;;
	9) /etc/lemp/menu/tienich/lemp-cai-dat-htop;;
	10) /etc/lemp/menu/lemp-sao-luu-sys;;
	11) /etc/lemp/menu/thay-doi-port-ssh;;
	12) /etc/lemp/menu/tienich/lemp-bat-tat-ssh-time-out;;
	13) /etc/lemp/menu/lemp-block-exploits-sql-injections-menu;;
	14) /etc/lemp/menu/lemp-chan-run-script-trong-folder-upload-menu;;
	15) /etc/lemp/menu/lemp-dat-mat-khau-bao-ve-folder-website;;
	16) /etc/lemp/menu/tienich/bat-tat-email-thong-bao-dang-nhap-server;;
	17) /etc/lemp/menu/lemp-bat-tat-tu-dong-chay-lemp;;
	18) /etc/lemp/menu/lemp-config-canh-bao-dung-luong-disc-trong-free-it;;
	19) clear && /etc/lemp/menu/tienich/lemp-restart-service;;
	20) clear && /etc/lemp/menu/tienich/toc-do-dot-net;;
	21) clear && /etc/lemp/menu/varnish/install-varnish;;
	22) clear && /etc/lemp/menu/tienich/update-wordpress-for-all-site;;
	23) clear && /etc/lemp/menu/tienich/install-composer;;
	24) clear && /etc/lemp/menu/nangcap-php/install-php;;
	25) clear && /etc/lemp/menu/nangcap-php/remove-php;;
	26) /etc/lemp/menu/go-bo-scripts;;
#	23) clear && lemp;;
	0) clear && lemp;;

    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;
esac

