#!/bin/bash
. /home/lemp.conf

# Kiểm tra phiên bản PHP đang chạy trên Apache
PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
PHP_INI_FILE="/etc/php/$PHP_VERSION/fpm/php.ini"

# Kiểm tra file php.ini
if [ ! -f $PHP_INI_FILE ]; then
clear
echo "========================================================================="
echo "LEMP không tìm thấy php.ini trên server"
# Thay đường dẫn cho Ubuntu nếu cần
/etc/lemp/menu/config-php/lemp-config-php.ini-menu
exit
fi
display_errors_value=$(grep display_errors "$PHP_INI_FILE" | awk -F'=' '{print $2}' | tr -d '\n' | awk '{$1=$1};1')


# Kiểm tra xem giá trị có rỗng không
if [ -z "$display_errors_value" ]; then
    clear
    echo "========================================================================="
    echo "LEMP không thể thực hiện chức năng này"
    /etc/lemp/menu/config-php/lemp-config-php.ini-menu
    exit
fi

if [ "$display_errors_value" == "Off" ]; then
    /etc/lemp/menu/lemp-dang-tat-display_errors
elif [ "$display_errors_value" == "On" ]; then
    /etc/lemp/menu/lemp-dang-bat-display_errors
fi
