#!/bin/bash
. /home/lemp.conf

# Kiểm tra trạng thái Redis và khởi động lại nếu đang chạy
if [ "$(systemctl is-active redis.service)" == "active" ]; then
    echo "Please wait...."; sleep 1
    systemctl restart redis.service
    clear
    echo "========================================================================= "
    echo "Restart Redis thành công!"
    /etc/lemp/menu/redis/lemp-before-redis-menu
else
    clear
    echo "========================================================================= "
    echo "Redis Cache đang tắt trên server."
    /etc/lemp/menu/redis/lemp-before-redis-menu
    exit
fi
