#!/bin/bash

# Kiểm tra trạng thái của IPv6
ipv6_status=$(sysctl net.ipv6.conf.all.disable_ipv6 | awk '{print $3}')

echo "Kiem tra trang thai cua IPv6"

if [ "$ipv6_status" -eq 0 ]; then
    echo "-----------------------------------------------------------------"
    echo "Dang tat IPv6..."
    sleep 1
    # Vô hiệu hóa IPv6
    sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null 2>&1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null 2>&1
    sysctl -w net.ipv6.conf.lo.disable_ipv6=1 > /dev/null 2>&1
    echo "-----------------------------------------------------------------"
    echo "IPv6 da duoc tat."
else
    echo "-----------------------------------------------------------------"
    echo "IPv6 dang tat. Khong can thuc hien thao tac nao."
fi

# Cập nhật cấu hình sysctl
if grep -q "net.ipv6.conf.all.disable_ipv6" /etc/sysctl.conf; then
    # Nếu đã có dòng này thì thay đổi giá trị
    sed -i "s/net.ipv6.conf.all.disable_ipv6 = .*/net.ipv6.conf.all.disable_ipv6 = 1/" /etc/sysctl.conf > /dev/null 2>&1
    sed -i "s/net.ipv6.conf.default.disable_ipv6 = .*/net.ipv6.conf.default.disable_ipv6 = 1/" /etc/sysctl.conf > /dev/null 2>&1
    sed -i "s/net.ipv6.conf.lo.disable_ipv6 = .*/net.ipv6.conf.lo.disable_ipv6 = 1/" /etc/sysctl.conf > /dev/null 2>&1
else
    # Nếu chưa có thì thêm vào và chuyển hướng đầu ra đến /dev/null
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf 
    echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf 
    echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf 
fi

# Áp dụng lại các thiết lập sysctl
sysctl -p > /dev/null 2>&1

echo "-----------------------------------------------------------------"
