#!/bin/bash

echo "Install php module..."
#yum -y install php php-common php-fpm php-gd php-devel php-json
#yum -y install php-curl php-pecl-zip $phppeclredis php-zip php-soap php-cli php-ldap php-mysqlnd php-pear-Net-SMTP php-enchant php-mysql php-pear $memcachedinstall php-opcache php-pdo php-zlib php-xml php-mbstring php-mcrypt
#sudo apt -y install php-pear
#sudo pear install Mail
#sudo pear install Net_SMTP
sudo DEBIAN_FRONTEND=noninteractive apt -yqq install php8.2 php8.2-curl php8.2-zip php8.2-soap php8.2-cli php8.2-snmp php8.2-pspell php8.2-gmp php8.2-ldap php8.2-bcmath php8.2-intl php8.2-imap libwww-perl liblwp-protocol-https-perl php8.2-enchant php8.2-common php8.2-fpm php8.2-gd php8.2-mysql php-pear php8.2-opcache php8.2-pdo php8.2-xml php8.2-mbstring php8.2-xmlrpc php8.2-tidy php8.2-memcache php8.2-redis php8.2-memcached php8.2-imagick

# Thay đổi phiên bản php trên hệ thống thành bản php8.2
sudo update-alternatives --set php /usr/bin/php8.2
#

clear
