#!/bin/bash
. /home/lemp.conf

# Kiểm tra trạng thái của Memcached
if [ "$(systemctl is-active memcached.service)" == "active" ]; then
    echo "Please wait...."; sleep 1
    systemctl restart memcached.service
    clear
    echo "========================================================================= "
    echo "Restart memcached thanh cong !"
    /etc/lemp/menu/memcache/lemp-before-memcache-menu
else
    clear
    echo "========================================================================= "
    echo "Memcached dang Disable tren server."
    /etc/lemp/menu/memcache/lemp-before-memcache-menu
    exit
fi
