#!/bin/bash
echo "========================================================================="
echo "Sử dụng chức năng này để gỡ bỏ LEMP khỏi máy chủ"
echo "-------------------------------------------------------------------------"
echo "Trong quá trình gỡ bỏ, toàn bộ dữ liệu website, database ... sẽ bị xóa"
echo "-------------------------------------------------------------------------"
echo "Máy chủ sẽ quay trở lại trạng thái như mới."
echo "========================================================================="
read -r -p "Bạn chắc chắn muốn gỡ bỏ LEMP? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
echo -n "Nhập [ OK ] để xác nhận: " 
read xacnhan
if [ ! "$xacnhan" = "OK" ]; then
clear
echo "========================================================================="
echo "Hủy gỡ bỏ LEMP"
/etc/lemp/menu/tienich/lemp-tien-ich
exit
fi
echo "-------------------------------------------------------------------------"
echo "Chuẩn bị gỡ bỏ LEMP, vui lòng đợi ...."
sleep 2

# Dừng các dịch vụ
#systemctl stop exim.service 
#systemctl disable exim.service
systemctl stop nginx.service 
systemctl disable nginx.service 
systemctl stop mariadb.service 
systemctl disable mariadb.service 
systemctl stop php*-fpm.service 
systemctl disable php*-fpm.service 
systemctl stop redis.service 
systemctl disable redis.service 

# Gỡ cài đặt các gói
sudo apt-get -y remove --purge mariadb* nginx php* exim mailutils httpd* syslog-ng htop pure-ftpd gcc g++ redis* memcached* unzip zip rar unrar rsync psmisc

# Xóa các tệp và thư mục không cần thiết
rm -rf /etc/nginx
rm -rf /etc/php-fpm.d
rm -rf /etc/php.d
rm -rf /etc/php.zts.d
rm -rf /etc/exim
rm -rf /var/lib/mysql
rm -rf /etc/mysql
rm -rf /etc/cron.d/*
rm -rf /etc/httpd
rm -rf /etc/syslog-ng
rm -rf /var/log/nginx
rm -rf /var/cache/ngx_pagespeed
rm -rf /etc/pure-ftpd
rm -rf /etc/motd 
rm -rf /home/*

# Xóa swap file nếu có
if [ -f /swapfile ]; then
    swapoff /swapfile
    rm -rf /swapfile
fi

# Xóa các tập tin cấu hình CSF nếu có
if [ -f /etc/csf/csf.conf ]; then
    cd /etc/csf
    sh uninstall.sh
    cd
fi

# Làm sạch và cập nhật
apt-get clean
apt-get -y update

clear
echo "========================================================================="
echo "Đã hoàn tất mọi thứ...!"
echo "-------------------------------------------------------------------------"
echo "Máy chủ sẽ khởi động lại sau 3 giây để hoàn tất...!"
sleep 3
reboot
exit
        ;;
    *)
    clear
    echo "========================================================================="
    echo "Hủy gỡ bỏ LEMP"
/etc/lemp/menu/tienich/lemp-tien-ich
        ;;
esac
