#!/bin/bash
. /home/lemp.conf
echo "========================================================================="
echo "Sử dụng chức năng này để tạo backup cho các file config và Vhost"
echo "-------------------------------------------------------------------------"
echo "Danh sách file và folder sẽ được backup: server.cnf, www.conf, php.ini"
echo "-------------------------------------------------------------------------"
echo "php-fpm.conf và Folder Nginx (chứa các file Vhost, SSL ...)" 
echo "========================================================================="
read -r -p "Bạn muốn sao lưu các file config & vhost? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
        echo "-------------------------------------------------------------------------"
        echo "Please wait ..."
        sleep 1
        rm -rf /home/$mainsite/private_html/Backupconfigandvhost*
        backupsys=$(date | md5sum | cut -c '1-12') 
        mkdir -p /usr/local/backup-system
        cp -r /etc/nginx /usr/local/backup-system/
        \cp -uf /etc/my.cnf.d/server.cnf /usr/local/backup-system/
        \cp -uf /etc/php/*/php.ini /usr/local/backup-system/   # Đường dẫn đến php.ini trên Ubuntu
        \cp -uf /etc/php/*/fpm/php-fpm.conf /usr/local/backup-system/  # Đường dẫn đến php-fpm.conf trên Ubuntu
        cp -r /etc/php/*/fpm/pool.d/www.conf /usr/local/backup-system/  # Đường dẫn đến www.conf trên Ubuntu
        cd /usr/local/backup-system/
        zip -r backupsys.zip *
        mv backupsys.zip /home/$mainsite/private_html/Backupconfigandvhost-$backupsys.zip
        cd
        rm -rf /usr/local/backup-system
        clear
        echo "========================================================================="
        echo "Link Download File Backup:"
        echo "-------------------------------------------------------------------------"
        echo "http://$serverip:$priport/Backupconfigandvhost-$backupsys.zip"
        /etc/lemp/menu/tienich/lemp-tien-ich
        ;;
    *)
       clear
       echo "========================================================================= "
       echo "Hủy bỏ tạo backup cho file config & Vhost."
       /etc/lemp/menu/tienich/lemp-tien-ich
       ;;
esac
