#!/bin/bash

. /home/lemp.conf

if [ -f /etc/csf/csf.conf ]; then
    test_csf=$(systemctl is-active csf)
    
    if [ "$test_csf" == "inactive" ]; then
        clear
        echo "========================================================================= "
        echo "CSF đang tắt trên server!"
        /etc/lemp/menu/CSF-Fiwall/lemp-csf-firewall-menu
    else
        clear
        echo "========================================================================= "
        echo "CSF Firewall nên được bật để bảo vệ VPS/Server!"
        echo "-------------------------------------------------------------------------"
        read -r -p "Bạn muốn tắt CSF FireWall? [y/N] " response
        case $response in
            [yY][eE][sS]|[yY]) 
                csf -x
                clear
                echo "========================================================================= "
                echo "Tắt CSF firewall thành công!"
                /etc/lemp/menu/CSF-Fiwall/lemp-csf-firewall-menu
                ;;
            *)
                clear
                echo "========================================================================= "
                echo "Bạn hủy bỏ việc tắt CSF Firewall!"
                /etc/lemp/menu/CSF-Fiwall/lemp-csf-firewall-menu
                exit
                ;;
        esac
    fi
else
    /etc/lemp/menu/CSF-Fiwall/lemp-tat-csf
    exit
fi
