#!/bin/bash
. /home/lemp.conf

PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")

if [ -f /etc/lemp/uploadsite ]; then
    uploadsite=$(cat /etc/lemp/uploadsite)
    if [ ! -d /home/$uploadsite/public_html ]; then
        rm -rf /etc/lemp/uploadsite
    fi
fi

if [ -f /etc/lemp/uploadsite ]; then
    filemanagedomain=$(cat /etc/lemp/uploadsite)
    checkfilemanagedomainconfig=$(grep auth_basic /etc/nginx/conf.d/$filemanagedomain.conf)
    if [ "$checkfilemanagedomainconfig" == "" ]; then
        Protection=Disable
    else
        Protection=Enable
    fi
fi

show_menu_filemanager () {
    prompt="Lua chon cua ban (0-Thoat):"
    options=("Setup File Manager" "Cau hinh Upload Max Filesize" "Bao Ve File Manager" "Thay User & Password Admin" "Thay Domain File Manager" "Remove File Manager")
    printf "=========================================================================\n"
    printf "                LEMP - Quan Ly VPS/Server by LEMP.VN \n"
    printf "=========================================================================\n"
    printf "                               File Manager \n"
    printf "=========================================================================\n"
    if [ ! -f /etc/lemp/uploadsite ]; then 
        printf "                      File Manager: Not Install \n"
    else
        printf "               File Manager: Installed | Protection: $Protection\n"
    fi
    printf "=========================================================================\n"
    if [ -f /etc/lemp/uploadsite ]; then
        filemanagedomain=$(cat /etc/lemp/uploadsite)
        printf "Link File Manager: http://$filemanagedomain\n"
        printf "=========================================================================\n"
    fi
    PS3="$prompt"
    select opt in "${options[@]}"; do 
        case "$REPLY" in
            1) /etc/lemp/menu/20_file-manager/lemp-cai-dat-web-upload-manage;;
            2) /etc/lemp/menu/20_file-manager/lemp-change-upload-file-size-limit-file-manage;;
            3) /etc/lemp/menu/20_file-manager/lemp-mat-khau-bao-ve-web-file-manage;;
            4) /etc/lemp/menu/20_file-manager/lemp-thay-mat-khau-web-file-manage;;
            5) /etc/lemp/menu/20_file-manager/lemp-thay-domain-web-file-manage;;
            6) /etc/lemp/menu/20_file-manager/lemp-xoa-website-upload-site;;
            0) clear && /bin/lemp;;
            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !"; continue;;
        esac
    done
}

check_nginx_service () {
    if [ "$(systemctl is-active nginx.service)" == "active" ]; then
        show_menu_filemanager 
    else
        clear
        echo "========================================================================"
        echo "Nginx service is not running"
        echo "------------------------------------------------------------------------"
        echo "LEMP trying to start it"
        echo "------------------------------------------------------------------------"
        echo "Please wait ..."
        sleep 5 ; clear
        systemctl start nginx.service
        clear
        echo "========================================================================"
        echo "Check Nginx service once again !"
        echo "------------------------------------------------------------------------"
        echo "please wait ..."
        sleep 5 ; clear
        if [ "$(systemctl is-active nginx.service)" == "active" ]; then
            show_menu_filemanager 
        else
            clear
            echo "========================================================================"
            echo "LEMP can not start Nginx Service"
            sleep 4 ;
            clear
            echo "========================================================================="
            echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
            lemp
        fi
    fi
}

if [ "$(systemctl is-active php${PHP_VERSION}-fpm.service)" == "active" ]; then
    check_nginx_service
else
    clear
    echo "========================================================================"
    echo "PHP${PHP_VERSION}-FPM service is not running"
    echo "------------------------------------------------------------------------"
    echo "LEMP trying to start it"
    echo "------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 5 ; clear
    systemctl start php${PHP_VERSION}-fpm.service
    clear
    echo "========================================================================"
    echo "Check PHP${PHP_VERSION}-FPM service once again !"
    echo "------------------------------------------------------------------------"
    echo "please wait ..."
    sleep 5 ; clear
    if [ "$(systemctl is-active php${PHP_VERSION}-fpm.service)" == "active" ]; then
        check_nginx_service
    else
        clear
        echo "========================================================================"
        echo "LEMP khong the khoi dong PHP-FPM Service"
        sleep 4 ;
        clear
        echo "========================================================================="
        echo "Rat tiec, PHP${PHP_VERSION}-FPM dang stopped. Hay bat len truoc khi dung chuc nang nay!"
        lemp
    fi
fi
