#!/bin/bash
. /home/lemp.conf
. /etc/lemp/pwprotect.default
if [ ! -d /etc/nginx/pwprotect ]; then
mkdir -p /etc/nginx/pwprotect
fi

if [ ! -f /etc/lemp/uploadsite ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat File Manager cho Server !"
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu
exit
fi
uploadsite=$(cat /etc/lemp/uploadsite)
if [ ! -f /etc/nginx/.htpasswd ]; then
clear
echo "========================================================================="
echo "Ban phai tao User va Mat khau mac dinh truoc khi chay chuc nang nay. Tao "
echo "-------------------------------------------------------------------------"
echo "User va Mat Khau mac dinh: lemp Menu => User & Password Mac Dinh."
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu
exit
fi

if [ "$(grep auth_basic_user_file /etc/nginx/conf.d/$uploadsite.conf)" == "" ] ; then 
echo "========================================================================="
echo "Su dung chuc nang nay de BAT bao ve domain File Manager. "
echo "-------------------------------------------------------------------------"
echo "Thong tin truy cap: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
echo "-------------------------------------------------------------------------"
read -r -p "Ban muon BAT bao ve domain File Manager ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
rm -rf /tmp/baovedomainfilemanage
   cat >> "/tmp/baovedomainfilemanage" <<END
sed -i "/server_name\ $uploadsite;/aauth_basic \"Authorization Required\";" /etc/nginx/conf.d/$uploadsite.conf
sed -i "/.*Authorization\ Required.*/aauth_basic_user_file  /etc/nginx/.htpasswd;" /etc/nginx/conf.d/$uploadsite.conf
END
chmod +x /tmp/baovedomainfilemanage
/tmp/baovedomainfilemanage
rm -rf /tmp/baovedomainfilemanage

systemctl reload nginx

;;
    *)
       clear 
echo "========================================================================= "
echo "Huy bo dat mat khau bao ve domain File Manager "
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Hoan thanh BAT bao ve domain File Manager."
echo "-------------------------------------------------------------------------"
echo "Thong tin truy cap: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu

else

echo "========================================================================="
echo "Chuc nang bao ve domain File Manager dang duoc BAT."
echo "-------------------------------------------------------------------------"
echo "Thong tin truy cap: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
echo "-------------------------------------------------------------------------"
read -r -p "Ban muon TAT chuc nang nay ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
sed -i '/auth_basic/d' /etc/nginx/conf.d/$uploadsite.conf

systemctl reload nginx

;;
    *)
       clear 
echo "========================================================================= "
echo "Huy bo TAT bao ve domain File Manager"
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Hoan thanh TAT mat khau bao ve domain File Manager "
/etc/lemp/menu/20_file-manager/lemp-web-upload-menu
fi
