#!/bin/bash
. /home/lemp.conf
curTime=$(date +%d)
checktruenumber='^[0-9]+$'
if [ $(id -u) != "0" ]; then
    printf "Co loi ! LEMP chi chay tren user root !\n"
    exit
fi



# Check LEMP Update
#/etc/lemp/menu/menucheck/check-lemp-update
# Check nginx Update
#/etc/lemp/menu/menucheck/check-nginx-update
#/etc/lemp/menu/menucheck/check-phpmyadmin-update
#/etc/lemp/menu/menucheck/check-csf-on
# kiem tra dung luong dia con lai
/etc/lemp/menu/menucheck/check-disk-usage



rm -rf /tmp/*ip*
rm -rf /tmp/showthongbao 


#find /etc/lemp/menu -type f -exec chmod 755 {} \;
prompt="Nhap lua chon cua ban:"
#options=("Thong tin thiet lap LEMP" "Them Website & Code" "Xoa website" "Backup & Restore Code" "Quan Ly Database" "Quan Ly phpMyAdmin" "Quan Ly Zend OPcache" "Quan Ly Memcached" "Quan Ly Redis Cache" "Quan Ly FTP Server" "Quan Ly Swap" "Quan Ly Cronjob"  "Quan Ly File Log" "Config Cau Hinh PHP" "Wordpress Blog Tools" "Quan Ly CSF Firewall" "Quan Ly IPtables Firewall" "Quan Ly BitTorrent Sync" "Quan Ly VPS Backup" "Linux Malware Detect" "Cai Dat File Manager" "Cai Dat Net2FTP" "Cai Dat NetData" "Cai Dat SSL (Let's Enctypt)" "Check & Block IP DOS" "Tien ich - Addons" "Update System" "Clear All Caches" "User & Password Mac Dinh" "Server Status" "Thoat")
options=("Them Website & Code" "Xoa website" "Backup & Restore Code" "Quan Ly Database" "Quan Ly phpMyAdmin" "Quan Ly Memcached" "Quan Ly Redis Cache" "Quan Ly FTP Server (dang loi chua ket noi duoc)" "Quan Ly Swap" "Quan Ly Cronjob"  "Quan Ly File Log" "Config Cau Hinh PHP" "Wordpress Blog Tools" "Quan Ly CSF Firewall" "Quan Ly IPtables Firewall" "Quan Ly VPS Backup" "Linux Malware Detect" "Cai Dat NetData" "Cai Dat SSL (Let's Enctypt)" "Check & Block IP DOS" "Tien ich - Addons" "Clear All Caches" "User & Password Mac Dinh" "Server Status" "Bat/Tat IPv6" "Thoat")

echo "========================================================================="
echo "                  LEMP - Quan Ly VPS/Server by VPS.VN                    "
echo "========================================================================="
echo "                             LEMP Menu                                   "
echo "========================================================================="

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in
	#0) /etc/lemp/finishedemail.sh;;
	1) clear && /etc/lemp/menu/lemp-befor-them-website-menu;;
    2) /etc/lemp/menu/lemp-befor-xoa-website;;
    3) clear && /etc/lemp/menu/3_backup-restore/lemp-sao-luu;;
    4) clear && /etc/lemp/menu/4_database/lemp-befor-them-xoa-database;;
    5) clear && /etc/lemp/menu/5_phpmyadmin/lemp-phpmyadmin-menu;;
    # Opcahe tren ubuntu co cai chung voi php-fpm roi nen ko can nua
	#6) clear && /etc/lemp/menu/opcache/lemp-before-opcache;;
    6) clear && /etc/lemp/menu/memcache/lemp-before-memcache-menu;;
    7) clear && /etc/lemp/menu/redis/lemp-redis-before-menu;;
    8) clear &&/etc/lemp/menu/ftpserver/lemp-ftpserver-menu;;
    9 )clear && /etc/lemp/menu/swap/lemp-them-xoa-swap-vps-menu;;
    10) clear && /etc/lemp/menu/crontab/lemp-cronjob-menu;;
    11) clear && /etc/lemp/menu/downloadlog/lemp-error-menu;;
    12) clear && /etc/lemp/menu/config-php/lemp-befor-lemp-config-php.ini-menu;;
    13) clear && /etc/lemp/menu/lemp-wordpress-tools-menu;;
    #14) clear && /etc/lemp/menu/pagespeed/before-lemp-pagespeed-menu;;"Nginx Pagespeed Manage" 
    14) /etc/lemp/menu/CSF-Fiwall/lemp-csf-firewall-before-menu;;
    15) clear && /etc/lemp/menu/lemp-iptables-firewall-manager-menu;;
    # 16) clear && /etc/lemp/menu/17_bitsync/lemp-bitsync-menu;; # ngien cuu sau, co the khong can thiet
    16) clear && /etc/lemp/menu/backup/lemp-befor-rsync;;
    17) clear && /etc/lemp/menu/lemp-maldet-menu;;
    #18) clear && /etc/lemp/menu/20_file-manager/lemp-web-upload-menu;;
    #19) clear && /etc/lemp/menu/21_net2ftp/lemp-net2ftp-menu;;
    18) clear && /etc/lemp/menu/22_netdata/lemp-netdata-menu;;
    19) clear && /etc/lemp/menu/23_ssl-free/lemp-letsencrypt-menu;;
    20) clear && /etc/lemp/menu/lemp-kiem-tra-ddos;;
    21) clear && /etc/lemp/menu/tienich/lemp-tien-ich;;
    #22) clear && /etc/lemp/menu/lemp-update-upgrade-service-menu;; # nang cap sau
    22) /etc/lemp/menu/clear-cache/lemp-clear-cache-xoa-cache-server;;
    23) /etc/lemp/menu/user-secure/dat-mat-khau-bao-ve-folder-mac-dinh;;
    24) clear && /etc/lemp/menu/vps-info/lemp-vps-info;;
	25) clear && /etc/lemp/menu/ipv6/bat_tat_ipv6;;
	26) clear && cat /etc/motd && killall -g lemp;; 
	0) clear && cat /etc/motd && killall -g lemp;; 
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
 
