#!/bin/sh

DATABASE_PASS=$(cat /tmp/passrootmysql)

# Thiết lập mật khẩu cho người dùng root
mariadb-admin -u root password "$DATABASE_PASS"

# Đảm bảo rằng không ai có thể truy cập vào máy chủ mà không cần mật khẩu
mariadb -u root -p"$DATABASE_PASS" -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DATABASE_PASS');"

# Xóa người dùng ẩn danh
mariadb -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"

# Xóa cơ sở dữ liệu thử nghiệm
mariadb -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%'"

# Làm cho các thay đổi có hiệu lực
mariadb -u root -p"$DATABASE_PASS" -e "FLUSH PRIVILEGES;"


 cat >> "/home/lemp.conf" <<END
mariadbpass="$DATABASE_PASS"
END
rm -rf /tmp/passrootmysql
#wget --no-check-certificate -q https://lemp.echbay.com/script/lemp/mysql_secure_installation.bak -O /bin/mysql_secure_installation
#wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/lemp-free/master/script/lemp/mysql_secure_installation_bak -O /bin/mysql_secure_installation
yes | cp -rf /opt/vps_lemp/script/lemp/mysql_secure_installation_bak /bin/mysql_secure_installation && chmod +x /bin/mysql_secure_installation
