#!/bin/bash 

if [ -f /etc/pure-ftpd/pure-ftpd.conf ]; then
    echo "========================================================================= "
    read -r -p "Ban muon remove FTP server ? [y/N] " response
    case $response in
        [yY][eE][sS]|[yY]) 
            echo "Chuan bi Remove FTP Server ... "
            sleep 1
            sudo DEBIAN_FRONTEND=noninteractive apt -yqq purge pure-ftpd*  
            rm -rf /etc/pure-ftpd
            rm -rf /etc/lemp/FTP-Account.info
            
            # Tạo lại tệp FTP-Account.info nếu nó không tồn tại
            if [ ! -f /etc/lemp/FTP-Account.info ]; then
                {
                    echo "========================================================================="
                    echo "KHONG DUOC XOA FILE NAY! "
                    echo "-------------------------------------------------------------------------"
                    echo "Neu ban xoa file nay, LEMP se khong chay !"
                    echo "-------------------------------------------------------------------------"
                    echo "Tat ca FTP User cho cac Domain tren VPS duoc liet ke phia duoi:"
                    echo "========================================================================="
                    echo ""
                } > /etc/lemp/FTP-Account.info
            fi
            
            clear
            # Chặn cổng 21 bằng ufw
            sudo ufw deny 21/udp
			sudo ufw deny 21/tcp
			sudo ufw deny 30000:50000/tcp
			sudo ufw deny 30000:50000/udp
            ;;
        *)
            clear 
            echo "========================================================================= "
            echo "Huy bo remove FTP Server "
            /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
            ;;
    esac
    
    clear 
    echo "========================================================================= "
    echo "LEMP hoan thanh remove FTP Server "
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
else
    clear
    echo "========================================================================= "
    echo "Ban chua cai dat FTP server "
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
    exit
fi
