#!/bin/bash
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi
prompt="Lua chon cua ban (0-Thoat):"
options=("Tao Tai Khoan FTP Cho Website" "Vo Hieu Hoa Tai Khoan FTP" "Thay Mat Khau Tai Khoan FTP" "Xem Thong Tin FTP Cua Website" "Go bo FTP Server" )
printf "=========================================================================\n"
printf "                LEMP - Quan Ly VPS/Server by LEMP.VN \n"
printf "=========================================================================\n"
printf "                            Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    
    1) /etc/lemp/menu/ftpserver/lemp-tao-ftp-user-cho-domain;;
    2) /etc/lemp/menu/ftpserver/lemp-xoa-ftp-user;;
    3) /etc/lemp/menu/ftpserver/lemp-thay-mat-khau-user-ftp;;
    4) /etc/lemp/menu/ftpserver/lemp-view-userftp-password;;
    5) /etc/lemp/menu/ftpserver/ftp-server-remove;;
    0) clear && lemp;;

    $(( ${#options[@]}+1 )) ) echo "";  clear && lemp;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done


