#!/bin/bash
. /home/lemp.conf 
if [ -f /etc/vsftpd/vsftpd.conf ]; then
clear
echo "========================================================================= "
echo "Phat hien VSFTPD duoc cai dat tren server. "
echo "-------------------------------------------------------------------------"
echo "De su dung day du chuc nang Quan Ly FTP Server"
echo "-------------------------------------------------------------------------"
echo "LEMP se Remove VSFTPD va xoa file cau hinh tren Server"
sleep 8
clear
echo "-------------------------------------------------------------------------"
echo "Please wait .............."
sleep 3
apt -y purge vsftpd  # Go VSFTPD va xoa cau hinh
clear
fi

if [ -f /etc/proftpd/proftpd.conf ]; then
clear
echo "========================================================================= "
echo "Phat hien ProFTPD duoc cai dat tren server. "
echo "-------------------------------------------------------------------------"
echo "De su dung day du chuc nang Quan Ly FTP Server"
echo "-------------------------------------------------------------------------"
echo "LEMP se Remove ProFTPD va xoa file cau hinh tren Server"
sleep 8
clear
echo "-------------------------------------------------------------------------"
echo "Please wait .............."
sleep 3
apt -y purge proftpd  # Go ProFTPD va xoa cau hinh
clear
fi

if [ ! -f /etc/lemp/menu/ftpserver/lemp-ftpserver-read ]; then
clear
printf "=========================================================================\n"
printf "                LEMP - Quan Ly VPS/Server by LEMP.VN \n"
printf "=========================================================================\n"
printf "                            Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""

echo "========================================================================="
echo "Su dung chuc nang nay de cai dat FTP Server cho Server"
echo "-------------------------------------------------------------------------"
echo "Sau khi cai dat FTP Server xong, ban co the tao tai khoan FTP cho tung"
echo "-------------------------------------------------------------------------"
echo "Website tren server. Mac dinh, ban khong the ket noi FTP vao Server bang "
echo "-------------------------------------------------------------------------"
echo "tai khoan root. Neu muon dang nhap tai khoan root, ban phai su dung sFTP"
echo "-------------------------------------------------------------------------"
echo "Ban dang nhap SFTP bang tai khoan root theo thong tin:"
echo "-------------------------------------------------------------------------"
echo "Host: sftp://$serverip"
echo "-------------------------------------------------------------------------"
echo "User: root | Password: Your_password "
echo "-------------------------------------------------------------------------"
echo "Port: Port SSH (mac dinh 22 - hoac Port SSH ban da thay)"
echo "-------------------------------------------------------------------------"
touch /etc/lemp/menu/ftpserver/lemp-ftpserver-read
read -p "Nhan [Enter] de tiep tuc ..."
clear
fi

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
/etc/lemp/menu/ftpserver/ftpserver-menu-khong
else
/etc/lemp/menu/ftpserver/ftpserver-menu-co
fi
