#!/bin/bash
. /home/lemp.conf

# Kiểm tra xem pure-ftpd đã được cài đặt chưa
if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
    clear
    echo "========================================================================= "
    echo "FTP Server chua duoc cai dat "
    echo "-------------------------------------------------------------------------"
    echo "Ban phai cai dat chuc nang Setup FTP server truoc"
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
    exit
fi

echo "========================================================================="
echo "Su dung chuc nang nay de tao FTP user cho website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap website ban muon them FTP user [ENTER]: " 
read website

if [ "$website" = "" ]; then
    clear
    echo "========================================================================="
    echo "Ban nhap sai, vui long nhap lai!"
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
    exit
fi

# Kiểm tra định dạng domain
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
    website=$(echo "$website" | tr '[A-Z]' '[a-z]')
    clear
    echo "========================================================================="
    echo "$website co ve khong phai la domain!"
    echo "-------------------------------------------------------------------------"
    echo "Ban vui long nhap lai!"
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
    exit
fi

# Kiểm tra xem website có tồn tại trong cấu hình nginx không
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
    clear
    echo "========================================================================="
    echo "Website $website khong ton tai tren he thong!"
    echo "-------------------------------------------------------------------------"
    echo "Ban hay nhap lai!"
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
    exit
fi

# Tạo file chứa thông tin người dùng FTP nếu chưa tồn tại
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
    touch /etc/pure-ftpd/pureftpd.passwd
fi

# Kiểm tra xem đã tạo tài khoản FTP cho website chưa
if [ ! -z "$(pure-pw list | grep "/home/$website/")" ]; then
    clear
    echo "========================================================================="
    echo "Ban da tao tai khoan FTP cho $website" 
    echo "-------------------------------------------------------------------------"
    echo "Thong tin tai khoan FTP:"
    echo "-------------------------------------------------------------------------"
    echo "IP: $serverip "
	echo "Port truy cap: 21"
    echo "-------------------------------------------------------------------------"
    echo "User: $(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $10}')"
    /etc/lemp/menu/ftpserver/lemp-ftpserver-menu
fi

echo "-------------------------------------------------------------------------"
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website chua tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "LEMP se tao tai khoan FTP cho $website ngay bay gio"
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 6

# Tạo tên đăng nhập và mật khẩu
#echo "$website" > /tmp/lempftp.txt
#sed -i 's/\./_/g' /tmp/lempftp.txt
#sed -i 's/\-/_/g' /tmp/lempftp.txt
#username=$(cat /tmp/lempftp.txt | tr -d '_' | cut -c1-30)
#password=$(date | md5sum | cut -c '3-23')

# Tạo tài khoản FTP
#( echo "${password}" ; echo "${password}" ) | pure-pw useradd "${username}" -u nginx -g nginx -d "/home/${website}" -m 
#pure-pw mkdb

# Tạo tên đăng nhập và mật khẩu
echo "$website" | sed 's/\./_/g; s/-/_/g' > /tmp/lempftp.txt
username=$(cat /tmp/lempftp.txt | cut -c1-30)
password=$(openssl rand -base64 12)  # Tạo mật khẩu ngẫu nhiên

# Tạo tài khoản FTP
( echo "${password}" ; echo "${password}" ) | pure-pw useradd "${username}" -u nginx -g nginx -d "/home/${website}" -m 
pure-pw mkdb



# Tạo file chứa thông tin tài khoản FTP nếu chưa tồn tại
if [ ! -f /etc/lemp/FTP-Account.info ]; then
    echo "=========================================================================" > /etc/lemp/FTP-Account.info
    echo "DUNG XOA FILE NAY " >> /etc/lemp/FTP-Account.info
    echo "-------------------------------------------------------------------------" >> /etc/lemp/FTP-Account.info
    echo "Neu ban xoa file nay, LEMP se khong chay !" >> /etc/lemp/FTP-Account.info
    echo "-------------------------------------------------------------------------" >> /etc/lemp/FTP-Account.info
    echo "Tat ca FTP User cho cac Domain tren VPS duoc liet ke phia duoi:" >> /etc/lemp/FTP-Account.info
    echo "=========================================================================" >> /etc/lemp/FTP-Account.info
    echo "" >> /etc/lemp/FTP-Account.info
fi

# Ghi thông tin tài khoản FTP vào file
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/lemp/FTP-Account.info

clear
echo "=========================================================================" 
echo "Tao tai khoan FTP cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin dang nhap:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "Port truy cap: 21"
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
