#!/bin/bash
. /home/lemp.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP Server chua duoc cai dat "
echo "-------------------------------------------------------------------------"
echo "Ban phai cai dat chuc nang Setup FTP Server truoc"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
exit
fi
echo "========================================================================="
echo "Su dung chuc nang nay de thay mat khau tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten website [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain!"
echo "-------------------------------------------------------------------------"
echo "Ban vui long nhap lai!"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Website $website khong ton tai tren he thong!"
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai!"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
exit
fi
if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP!"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
fi

echo "========================================================================="
echo "Phat hien tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP hien tai:"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $7}')  |  Password: $(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $10}')"
echo "-------------------------------------------------------------------------"
echo "Bay gio LEMP se thay mat khau moi cho: $(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "========================================================================="
echo "Please wait ....."
sleep 7
#username=$(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $7}')
#mkmoi=`date |md5sum |cut -c '3-23'`
#( echo -e "${mkmoi}\n${mkmoi}" ) | pure-pw passwd $username
#pure-pw mkdb

username=$(grep "/home/$website/" /etc/lemp/FTP-Account.info | awk 'NR==1 {print $7}')
mkmoi=$(openssl rand -base64 12)  # Tạo mật khẩu ngẫu nhiên

( echo -e "${mkmoi}\n${mkmoi}" ) | pure-pw passwd $username
pure-pw mkdb


sed -i "/\/home\/$website/d" /etc/lemp/FTP-Account.info
echo "FTP Account for $website | Username: $username | Password: $mkmoi | dd /home/$website/ " >> /etc/lemp/FTP-Account.info
clear
echo "========================================================================= "
echo "Thay mat khau tai khoan FTP cua $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login moi:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "Port truy cap: 21"
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $mkmoi"
/etc/lemp/menu/ftpserver/lemp-ftpserver-menu
