#!/bin/bash

# Gỡ bỏ Varnish trên Ubuntu đã cài đặt từ packagecloud.io

remove_varnish_repo () {
    # Xóa repository Varnish
    rm -rf /etc/apt/sources.list.d/varnishcache*
}

echo "========================================================================="

# Kiểm tra phiên bản Varnish hiện tại
if [ -f /etc/lemp/varnish.version ]; then
    printf "                   Phiên bản Varnish hiện tại: $(cat /etc/lemp/varnish.version) \n"
else
    printf "                  Varnish Cache chưa được cài đặt\n"
    printf "          Hoặc không được cài đặt thông qua LEMP \n"
fi

echo "-------------------------------------------------------------------------"
varnishd -V
echo "========================================================================="
echo "Xóa repo: rm -rf /etc/apt/sources.list.d/varnishcache_varnish74.list"
echo "========================================================================="

echo -n "Bạn có muốn gỡ bỏ Varnish Cache không? [y/N] "
read goBoVarnish

if [ "$goBoVarnish" = "y" ]; then
    clear
    echo "Ok ok! Chuẩn bị gỡ bỏ Varnish Cache..."
    sleep 2

    # Kiểm tra và gỡ bỏ Varnish
    dpkg -l | grep -i varnish
    sudo apt-get -y remove --purge varnish
    remove_varnish_repo
    sudo apt-get update
    dpkg -l | grep -i varnish
else
    echo "Hủy bỏ thao tác: gỡ bỏ Varnish Cache..."
    sleep 2
    clear
fi

# Chạy lại lệnh cài đặt (nếu cần)
#/etc/lemp/menu/varnish/install-varnish
