#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish40/install#bash-rpm

/etc/lemp/menu/varnish/install-varnish-begin
echo "4.1" >> /etc/lemp/varnish.version

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish41/script.rpm.sh | sudo bash

/etc/lemp/menu/varnish/install-varnish-end
